name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get date and hash
      id: prep
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        SHORT_SHA="$(echo $GITHUB_SHA | head -c 7)"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        echo "::set-output name=date::$(date +'%Y%m%d')"
        echo "::set-output name=sha::$SHORT_SHA"

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/sensitive-web:latest
          ${{ secrets.DOCKER_USERNAME }}/sensitive-web:${{ steps.prep.outputs.date }}-${{ steps.prep.outputs.sha }}

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add SSH key to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy with docker-compose
      run: |
        ssh -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.DOCKER_COMPOSE_PATH }}
          docker-compose pull
          docker-compose up -d
        EOF
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}